version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      cargo-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 10

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: weekly
    groups:
      pre-commit-hooks:
        patterns: ["*"]
    open-pull-requests-limit: 10
