[package]
name = "rust-statement-spacing-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.10"
rust-statement-spacing-core = { path = "../crates/core" }
rust-statement-spacing-syntax = { path = "../crates/syntax" }

[[bin]]
name = "source_round_trip"
path = "fuzz_targets/source_round_trip.rs"
test = false
doc = false
bench = false

[workspace]
